version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - '8080:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2081
      - POSTGRES_DB=nest
    networks:
      - freecodecamp
networks:
  freecodecamp: